### PR TITLE
remove extra semi colon to fix webpack 5 build issue.

### PR DESCRIPTION
**Pull request by sahi1422**
https://github.com/Semantic-Org/Semantic-UI-CSS/issues/75

### CODE REVIEW

**Comment by sahi1422** [comment]
@jlukic @xiaohanyu @nooitaf @levithomason , can you please have a look at this PR and let me help merge it? This is a kind of blocking issue and makes users to choose between webpack5 and Semantic UI.

**Comment by Sahil-rll** [comment]
@nooitaf , thanks for having a look. Would you please give some idea how long it can take to get this PR merged?

**Comment by levithomason** [comment]
Thanks for the find and fix. I believe this file is generated in a build, possibly from the main repo. I will try to take a look at it soon.

**Comment by sahi1422** [comment]
@levithomason , any updates?

**Review by jlukic — APPROVED** [review]

**Comment by sahi1422** [comment]
@jlukic @levithomason , thanks for looking into this. I see the PR got merged. When will these changes be reflected in the NPM package?

**Comment by aruna-x** [comment]
I used this package with no issue before today. Unfortunately the recent merge may have cause me and a few of my colleagues to get an error related to the extra semi colon now. (We all started new projects today.)

**Pull request merged**
