### PR TITLE
Remove extra semi-colon from step.css also

### PR DESCRIPTION
**Pull request by sahi1422**
@jlukic @levithomason , I forgot to remove the semi-colon from the `step.css`

https://github.com/Semantic-Org/Semantic-UI-CSS/pull/76

### CODE REVIEW

**Comment by guslen** [comment]
@Semantic-Pusher-Robot  ?

**Comment by guslen** [comment]
@fniessink or maybe @peacekeeper  or @sahi1422 ?

**Review by peacekeeper — APPROVED** [review]

**Comment by guslen** [comment]
@jlukic will you merge this? Also, a version bump would be excellent. 😄

**Comment by guslen** [comment]
@peacekeeper, do you know who can merge this pull request?

**Comment by peacekeeper** [comment]
Sorry I don't know.. I also wish this could be merged.

**Comment by guslen** [comment]
@peacekeeper 
> Sorry I don't know.. I also wish this could be merged.

I sent an email to info@semantic-ui.com with this content:
Subject: 

> Who can merge PR in Semantic css

Content: 

> Hi,
> We need a merge and a version bump for semantic-ui-css. jlucik doesn't seem to react even after tagging him. I don't know who is in charge of the repo.
> this is the PR in question https://github.com/Semantic-Org/Semantic-UI-CSS/pull/77#issue-1083335401
> 
> Thank you for the help.
> 
> Best regards,
> Gustav Lennart Voigt

**Comment by jlukic** [comment]
These repos are automatically generated from the main Semantic UI repo. 

You will need to make any changes in the `src/` folder if there's a typo. 

You can find the correct file here
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/elements/step.overrides#L5

**Comment by jlukic** [comment]
I've gone ahead and run the release bot to publish the changes from the main repo @sahi1422

**Pull request closed without merging**
